@startuml
'https://plantuml.com/sequence-diagram
!theme mars

title Machine to Machine Requests

autonumber

actor Client as C
participant "Authorization Server" as AS

C -> AS: request for Client Credential
rnote over AS
POST /token
BODY: x-www-form-urlencoded
grant_type=client_credential
client_id=<client_id>
client_secret=<client_secret>
scope=<scopes> (Add 'offline_access' for refresh token never expires)
endrnote
AS --> C: Response with Access Token + Refresh Token

@enduml