@startuml
'https://plantuml.com/sequence-diagram
!theme mars

title Password Credential

autonumber

actor Client as C
participant "Authorization Server" as AS

C -> AS: request for Client Credential
rnote over AS
POST /token
BODY: x-www-form-urlencoded
grant_type=password
username=<username>
password=<password>
client_id=<client_id>
client_secret=<client_secret>
scope=<scopes>
endrnote
AS --> C: Response with Access Token + Refresh Token

@enduml