@startuml
'https://plantuml.com/class-diagram
!theme mars

interface PasswordEncoder {
  +encode(CharSequence rawPassword): String
  +matches(CharSequence rawPassword, String encodedPassword): boolean

  +upgradeEncoding(String encodedPassword): boolean
}

@enduml